baseURL = ""
defaultContentLanguage = "en"
theme = "ublogger"
themesDir = "themes"
title = "uBlogger"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
publishDir = "public"

[languages.en]
weight = 1
languageCode = "en"
languageName = "English"
hasCJKLanguage = false
paginate = 12
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[[languages.en.menu.main]]
identifier = "posts"
pre = ""
post = ""
name = "Posts"
url = "/posts/"
title = ""
weight = 1

[[languages.en.menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 2

[[languages.en.menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 3

[[languages.en.menu.main]]
identifier = "documentation"
pre = ""
post = ""
name = "Docs"
url = "/categories/documentation/"
title = ""
weight = 4

[[languages.en.menu.main]]
identifier = "about"
pre = ""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 5

[[languages.en.menu.main]]
identifier = "github"
pre = "<i class='fab fa-github fa-fw'></i>"
post = ""
name = ""
url = "https://github.com/upagge/ublogger"
title = "GitHub"
weight = 6

  [languages.en.params]
  description = "About uBlogger Theme"
  keywords = [ "Theme", "Hugo" ]

    [languages.en.params.app]
    title = "uBlogger"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

    [languages.en.params.search]
    enable = true
    type = "algolia"
    contentLength = 4_000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

      [languages.en.params.search.algolia]
      index = "index.en"
      appID = "PASDMWALPK"
      searchKey = "b42948e51daaa93df92381c8e2ac0f93"

    [languages.en.params.home]
    rss = 10

      [languages.en.params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.png"
      title = "uBlogger | Hugo Theme"
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      social = true
      disclaimer = ""

      [languages.en.params.home.posts]
      enable = true
      paginate = 6

    [languages.en.params.social]
    GitHub = "xxxx"
    Linkedin = ""
    Twitter = "xxxx"
    Instagram = "xxxx"
    Facebook = "xxxx"
    Telegram = "xxxx"
    Medium = ""
    Gitlab = ""
    Youtubelegacy = "xxxx"
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "xxxx@xxxx.com"
    DockerHub = ""
    Discord = "xxxxxxxxx"
    Leanpub = ""
    Udemy = ""
    RSS = true

      [languages.en.params.social.Mastodon]
      id = "@xxxx"
      prefix = "https://mastodon.technology/"

[params]
version = "2.0.X"
defaultTheme = "auto"
gitRepo = "https://github.com/upagge/dolboblog-theme"
fingerprint = ""
dateFormat = "2006-01-02"
images = [ "/logo.png" ]

  [params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

    [params.header.title]
    logo = ""
    name = "uBlogger"
    pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
    post = ""

  [params.footer]
  enable = true
  custom = ""
  hugo = true
  copyright = true
  author = true
  since = 2_019
  icp = ""
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
  paginate = 20
  dateFormat = "01-02"
  rss = 10

  [params.list]
  paginate = 20
  dateFormat = "01-02"
  rss = 10

  [params.comment]
  enable = true

    [params.comment.remark42]
    enable = true
    host = "https://comments.upagge.ru"
    site = "documentation"
    locale = "en"

    [params.comment.disqus]
    enable = false
    shortname = ""

    [params.comment.gitalk]
    enable = false
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

    [params.comment.valine]
    enable = false
    appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
    appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
    placeholder = ""
    avatar = "mp"
    meta = ""
    pageSize = 10
    lang = ""
    visitor = true
    recordIP = true
    highlight = true
    enableQQ = false
    serverURLs = "https://"
    emoji = ""

    [params.comment.facebook]
    enable = false
    width = "100%"
    numPosts = 10
    appId = ""
    languageCode = ""

    [params.comment.telegram]
    enable = false
    siteID = ""
    limit = 5
    height = ""
    color = ""
    colorful = true
    dislikes = false
    outlined = false

    [params.comment.commento]
    enable = false

    [params.comment.utterances]
    enable = false
    repo = ""
    issueTerm = "pathname"
    label = ""
    lightTheme = "github-light"
    darkTheme = "github-dark"

  [params.page]
  hiddenFromHomePage = false
  hiddenFromSearch = false
  twemoji = false
  ruby = true
  fraction = true
  fontawesome = true
  linkToMarkdown = true
  rssFullText = false

    [params.page.toc]
    enable = true
    keepStatic = false
    auto = true

    [params.page.code]
    copy = true
    maxShownLines = 10

    [params.page.math]
    enable = false
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    copyTex = true
    mhchem = true

    [params.page.mapbox]
    accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    navigation = true
    geolocate = true
    scale = true
    fullscreen = true

    [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = true
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = true
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = true
    Renren = false
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false

    [params.page.library]
    css = { }
    js = { }

    [params.page.seo]
    images = [ ]

      [params.page.seo.publisher]
      name = "xxxx"
      logoUrl = "/images/avatar.png"

  [params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

  [params.seo]
  image = "/images/Apple-Devices-Preview.png"
  thumbnailUrl = "/images/screenshot.png"

  [params.analytics]
  enable = true

    [params.analytics.google]
    id = ""
    gtag = false
    anonymizeIP = true

    [params.analytics.fathom]
    id = ""
    server = ""

    [params.analytics.yandex]
    id = "70532758"

  [params.cookieconsent]
  enable = false

    [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

  [params.cdn]
  data = "jsdelivr.yml"

  [params.compatibility]
  polyfill = false
  objectFit = false

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6

[author]
name = "upagge.en"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[Permalinks]
posts = ":filename"

[privacy]
googleAnalytics = { }

  [privacy.twitter]
  enableDNT = true

  [privacy.youtube]
  privacyEnhanced = true

[mediaTypes."text/plain"]
suffixes = [ "md" ]

[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "MarkDown" ]
section = [ "HTML", "RSS" ]
taxonomy = [ "HTML", "RSS" ]
taxonomyTerm = [ "HTML" ]
